import Head from 'next/head'
import { format, parseISO, add } from 'date-fns';
import { blogPosts } from '../../data';

export default function BlogPage({title,date,content}) {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="border-b-2 border-gray-200 mb-4">
          <h1 className="text-3xl font-bold">{title}</h1>
          <p className="text-gray-600 text-sm">{format(parseISO(date), 'MMM do, uuu')}</p>
        </div>
        <p>{content}</p>
      </main>

    </div>
  )
}

export async function getStaticProps(context) {
    // console.log(context);
    const { params } = context;
    return {
        props: blogPosts.find(item => item.slug === params.slug),
    };
};

export async function getStaticPaths() {
    return {
        paths: blogPosts.map((post) => ({
          params: {
            slug: post.slug,
          },
    })),
    fallback: false,
  };
}