import Head from 'next/head'
import Link from 'next/link';
import { blogPosts } from '../data'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          My Blog
        </h1>
      </main>

      <div>
        {blogPosts.map((post) => {
          return (
            <div key={post.slug}>
              <div>
                <Link href={`/blog/${post.slug}`}>
                  {post.title}
                </Link>
              </div>
              <div>{post.date.toString()}</div>
              <div>{post.content}</div>
            </div>
          )
        })}
      </div>

    </div>
  )
}
